### ISSUE TITLE
Expected to find exactly one matching array item for path '/instance_groups/name=create-uaa-client' but found 0

### ISSUE THREAD

**Issue by hfrenzel** [cloudfoundry-community/logsearch-boshrelease#132]
Hi,

trying to apply `deployment/operations/push-cloudfoundry-kibana.yml` ops results in:

`Expected to find exactly one matching array item for path '/instance_groups/name=create-uaa-client' but found 0`

Probably a question mark in [line 8](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/deployment/operations/push-cloudfoundry-kibana.yml#L8) is missing?

We are using the following deployment-/ops-files:
* `deployment/logsearch-deployment.yml`
* `deployment/operations/cloudfoundry.yml`
* `deployment/operations/push-cloudfoundry-kibana.yml`

b/r

**Comment by Infra-Red** [comment]
Hi @hfrenzel. Thanks for reporting the issue! The problem is that in `cloudfoundry.yml` ops file we are using collocated errands and `create-uaa-client` job is collocated with `maintenance` instance group.

https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/158fbc782622498ced4d76a4a9c574eaf16f83e1/deployment/operations/cloudfoundry.yml#L2-L6

I will fix this issue right now.

**Comment by hfrenzel** [comment]
Great! Thanks for the fast fix :)
