### ISSUE TITLE
Delay allocation script should not run on parser instances.

### ISSUE THREAD

**Issue by Infra-Red** [cloudfoundry-community/logsearch-boshrelease#45]
Since parser instances have elasticsearch job deployed for service discovery, we should skip delay allocation `post-start` script on this instances.
WDYT? @axelaris @jmcarp

**Comment by jmcarp** [comment]
Sure, we could wrap https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/elasticsearch/templates/bin/post-start.erb#L43-L44 in a check that we're looking at a data node. I don't think we want to skip the entire `post-start`, since it's still useful to verify that the parser node is responding to the health check.

**Comment by axelaris** [comment]
Fixed by https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/46
