### ISSUE TITLE
Support for ELK 5 

### ISSUE THREAD

**Issue by bonzofenix** [cloudfoundry-community/logsearch-boshrelease#50]
At Allstate we been using Logsearch on version 204. We been working in upgrading the Logstash stack to support V5.

We decided to take on this work because we want some filters updated such as the throttle filter which in logstash v5 supports multi threading.

Here are some of the things to notice:

* We are removing default RELP support as it is now provided.
* v2 -> V5 requires a [full restart](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html)  of the Elasticsearch cluster.
* It requires a refactor and compatible release of logsearch-for-cloudfoundry as some of the filter's syntax is changes in logstash v5. (We would take care of this work too)

the PR is almost prepared. We were wondering how this would affect other Logsearch users and if this would be something other users would be intrested in.

@jmcarp @axelaris @Infra-Red

**Comment by mogul** [comment]
It'd be very welcome on the cloud.gov team!

**Comment by axelaris** [comment]
We also started to work on Elasticsearch V5 release, but I'm not sure how much time it will take.
So I will be more than happy to merge your PR if it will come faster

**Comment by Isaacjcollier** [comment]
@axelaris we submitted the PR. While we are working on merging it, we will get started on logsearch-for-cloudfoundry refactor in the meantime.

@bonzofenix & @isaacjcollier

**Comment by bonzofenix** [comment]
#51 Is ready for merging. Is there any merging/releasing process establish for this project?

**Comment by axelaris** [comment]
Yes, we're going to deploy it in our test environment to make sure it working as expected.

**Comment by Isaacjcollier** [comment]
Logsearch-for-cloudfoundry PR with elk5 support is ready too:

 https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/240

**Comment by Infra-Red** [comment]
@axelaris @Isaacjcollier @bonzofenix Just verified update from v2 -> v5 on running cluster, upgrade goes without problems with `--recreate` flag. One notice that you should disable `canaries` and set `max_in_flight` value equal to number of data nodes for elasticsearch_data update properties because `post-start` script wait for green cluster status, but that can't happen because of incompatible elasticsearch versions, so all elasticsearch_data nodes must be updated simultaneously. I'll keep you updated with information about the upgrade.

**Comment by bonzofenix** [comment]
@Infra-Red Thank for the input, let us know which are your findings so that we can update the readme before doing a final release.
