### ISSUE TITLE
Cannot deploy new cluster without disabling elasticsearch post-start

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/logsearch-boshrelease#62]
Seems like an initial cluster when deploying the canary node can't spin up properly, because there's only one data-node, and it's in a yellow-state. The user experience for "deploy initially disabling post start, then redeploy to enable it" seems sub-optimal.

Would things work better if it moved from post-start to post-deploy?

**Comment by Infra-Red** [comment]
@geofffranks Are you trying to upgrade existing Logsearch cluster or deploying from scratch?

**Comment by geofffranks** [comment]
Deploying from scratch

**Comment by Infra-Red** [comment]
Both jobs elasticsearch_master/elasticsearch_data have `serial: true` in update section and cluster should not get any data during the deployment process since ingestor/parser jobs are beginning to update only when elasticsearch is in healthy and empty state.
https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/v206.0.1/templates/logsearch-jobs.yml#L145

**Comment by geofffranks** [comment]
Something was generating a .kibana index, and it was yellow.

**Comment by Infra-Red** [comment]
Make sure that all jobs are updated in the correct order.

**Comment by geofffranks** [comment]
They seem to be. Had a kibana app running in the background, as logsearch got in such an unworkable state I had to bosh delete-deployment + recreate (but the cf app for kibana stayed up).


Regardless, would moving the post-start script to post-deploy fix this, and the issues encountered when deploying using bosh2 azs?

**Comment by Infra-Red** [comment]
I guess that this Kibana app is part of a previous Logsearch deployment ;)
Bosh2 require additional steps only for upgrade ELK 2 -> ELK 5.
I don't like idea with `post-deploy` scripts until they will be enabled by default.

**Comment by jmcarp** [comment]
@geofffranks: the recommended procedure for an elastic rolling restart is to wait for each node to rejoin the cluster and finish reallocating shards before moving on to the next: https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html. That's why we added the post-start script. Do you need to start kibana before the cluster is healthy?

By the way, which issues did you run into with bosh2 azs?
