### ISSUE TITLE
Optionally swap redis for logstash persistent queue

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/logsearch-boshrelease#72]
Now that logstash supports [persistent queues](https://www.elastic.co/guide/en/logstash/current/persistent-queues.html), operators might not need to use redis--especially because the redis queue used here is a single point of failure. This might be as simple as configuring the current `ingestor` job to output directly to elastic. If so, would you all be interested in a patch with updated templates that drop the `queue` and `parser` jobs and configure the `ingestor` to use persistent queues and output to elastic?

cc @wjwoodson @cnelson

**Comment by Infra-Red** [comment]
Added in https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/f3c7b61b2fc4a1910af1e33932053333d58c7512%5E%5E.
I have moved redis job to logsearch-for-cloudfoundry repo since it's no longer needed in current repo. Will keep this issue opened for some time in case I missed something.
